# 学术服务
items:
- name: "<strong>Reviewer</strong>: IEEE Transactions on Software Engineering (TSE), ACM Transactions on Software Engineering and Methodology (TOSEM), Automated Software Engineering (ASE)"
  name_zh: "<strong>期刊审稿</strong>：IEEE TSE、ACM TOSEM、ASE"
- name: "<strong>Reviewer</strong>: NeurIPS 2026"
  name_zh: "<strong>会议审稿</strong>：NeurIPS 2026"
